// Define a 'Person' class
data class Person(val name: String, // data class 'Person'
                    val age: Int? = null // nullable type 'Int?'
                    )


fun main(args: Array<String>) { // top-level function
    // create a collection of people
    // declare and create a list
    val persons = listOf(Person("Alice"),
                        Person("Bob", age = 29))    // named argument

    // find the oldest one
    // call a method 'maxBy' of list
    val oldest = persons.maxBy { it.age ?: 0 }  // lambda expression, elvis operator '?:'

    // Print the result
    // use a built-in function 'println'
    // string template
    println("(string template)The oldest is: $oldest")  // string temmplate
    // string formatting
    println("(string.format())The oldest is: %s".format(oldest))

    // declare an integer
    val my_int = 10
    // string template
    println("my_int: $my_int\nmy_int*2: ${my_int*2}")
}

//////// Console output ////////
// (string template)The oldest is: Person(name=Bob, age=29) // autogenerated toString
// (string.format())The oldest is: Person(name=Bob, age=29)
// my_int: 10
// my_int*2: 20